name: 'Auto Comment Merge Conflict'
description: 'Github Action to automatically add a comment (and a label) to alert developers when there are merge conflicts'
author: 'CodyTseng'
branding:
  icon: 'git-merge'
  color: 'red'
inputs:
  token:
    required: true
    description: 'GitHub token'
  comment-body:
    required: false
    description: 'Comment body'
    default: 'Merge Conflict'
  wait-ms:
    required: false
    description: 'Milliseconds between retries'
    default: 3000
  max-retries:
    required: false
    description: 'The number of retries when a PR mergeable status is unknown'
    default: 5
  label-name:
    required: false
    description: 'Label name'
outputs:
  new-conflicting-prs:
    description: 'List of all new conflicting PRs (json string)'
  new-mergeable-prs:
    description: 'List of all new mergeable PRs (json string)'
runs:
  using: 'node16'
  main: 'dist/index.js'
