name: 'Auto Comment Merge Conflict'
description: 'Github Action to automatically add comments to alert developers when there are merge conflicts'
author: 'CodyTseng'
branding:
  icon: 'git-merge'
  color: 'red'
inputs:
  token:
    required: true
    description: 'GitHub token'
  comment-body:
    required: false
    description: 'Comment body'
    default: 'Merge Conflict'
  wait-ms:
    required: false
    description: 'Milliseconds between retries'
    default: 3000
  max-retries:
    required: false
    description: 'The number of retries when a PR mergeable status is unknown'
    default: 5
runs:
  using: 'node16'
  main: 'dist/index.js'
